name: partitioncache-rocksdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - rocksdb
  - pip:
    # Python dependencies will be installed via pip install -e ".[testing,db]"
    # This env file only specifies conda packages that can't be installed via pip