name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  PYTHON_VERSION: "3.12"

jobs:
  build-postgres-image:
    name: Build PostgreSQL Image with Extensions
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: sha-${{ steps.sha.outputs.short }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get short SHA
      id: sha
      run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/mpoppinga/postgres-test-extensions
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=sha-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push PostgreSQL image
      uses: docker/build-push-action@v5
      with:
        context: .github/docker/postgres-cron
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

  integration-tests:
    name: ${{ matrix.test-pattern.name }}
    runs-on: ubuntu-latest
    needs: build-postgres-image
    
    strategy:
      fail-fast: false
      matrix:
        test-pattern:
          - name: "PostgreSQL Backends"
            pattern: "postgresql"
            suffix: "pg"
            parallel: true
            requires_redis: false
          - name: "Redis Backends"
            pattern: "redis"
            suffix: "redis"
            parallel: true
            requires_redis: true
          - name: "RocksDB Backends"
            pattern: "rocksdb"
            suffix: "rocksdb"
            parallel: false
            requires_redis: false
          - name: "Queue Processing"
            pattern: "queue"
            suffix: "queue"
            parallel: false
            requires_redis: false
          - name: "CLI Tools"
            pattern: "test_cli"
            suffix: "cli"
            parallel: true
            requires_redis: false

    services:
      postgres:
        image: ghcr.io/mpoppinga/postgres-test-extensions:${{ needs.build-postgres-image.outputs.image-tag }}
        env:
          POSTGRES_DB: partitioncache_integration
          POSTGRES_USER: integration_user
          POSTGRES_PASSWORD: integration_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U integration_user -d partitioncache_integration"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      # Define a unique database name for each job
      UNIQUE_DB_NAME: partitioncache_integration_${{ matrix.test-pattern.suffix }}_${{ github.run_id }}
      TEMPLATE_DB_NAME: partitioncache_integration
      
      # PostgreSQL configuration
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: integration_user
      PG_PASSWORD: integration_password
      
      # Database configuration
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: integration_user
      DB_PASSWORD: integration_password
      
      # Queue configuration
      PG_QUEUE_HOST: localhost
      PG_QUEUE_PORT: 5432
      PG_QUEUE_USER: integration_user
      PG_QUEUE_PASSWORD: integration_password
      QUERY_QUEUE_PROVIDER: postgresql
      
      # Redis configuration
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_CACHE_DB: 0
      REDIS_BIT_DB: 1
      REDIS_BIT_BITSIZE: 200000
      REDIS_SET_HOST: localhost
      REDIS_SET_PORT: 6379
      REDIS_SET_DB: 0
      
      # Cache backend configuration
      PG_ARRAY_CACHE_TABLE_PREFIX: ci_array_cache
      PG_BIT_CACHE_TABLE_PREFIX: ci_bit_cache
      PG_BIT_CACHE_BITSIZE: 200000
      PG_ROARINGBIT_CACHE_TABLE_PREFIX: ci_roaring_cache
      
      # RocksDB configuration
      ROCKSDB_PATH: /tmp/ci_rocksdb
      ROCKSDB_BIT_PATH: /tmp/ci_rocksdb_bit
      ROCKSDB_BIT_BITSIZE: 200000
      ROCKSDB_DICT_PATH: /tmp/ci_rocksdict

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: .github/micromamba-env.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install PartitionCache
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[testing,db]"
        pip install pytest-xdist  # Additional for parallel execution

    - name: Create and configure test database
      shell: micromamba-shell {0}
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..30}; do
          if python -c "import psycopg; psycopg.connect('postgresql://integration_user:integration_password@localhost:5432/$TEMPLATE_DB_NAME')" 2>/dev/null; then
            echo "PostgreSQL ready"
            break
          fi
          sleep 2
        done

        echo "Creating test database: $UNIQUE_DB_NAME from template $TEMPLATE_DB_NAME"
        python -c "
        import os
        import psycopg
        from psycopg import sql
        db_name = os.environ['UNIQUE_DB_NAME']
        template_db = os.environ['TEMPLATE_DB_NAME']
        conn_str = f'postgresql://integration_user:integration_password@localhost:5432/{template_db}'
        with psycopg.connect(conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(sql.SQL('CREATE DATABASE {} TEMPLATE {}').format(
                    sql.Identifier(db_name),
                    sql.Identifier(template_db)
                ))
        "

        # Set the database name for subsequent steps
        echo "PG_DBNAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV
        echo "DB_NAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV
        echo "PG_QUEUE_DB=$UNIQUE_DB_NAME" >> $GITHUB_ENV

        if [[ "${{ matrix.test-pattern.requires_redis }}" == "true" ]]; then
          echo "Waiting for Redis..."
          for i in {1..30}; do
            if redis-cli -h localhost -p 6379 ping >/dev/null 2>&1; then
              echo "Redis ready"
              break
            fi
            sleep 2
          done
        fi

    - name: Verify extensions
      shell: micromamba-shell {0}
      run: |
        python -c "
        import os
        import psycopg
        db_name = os.environ['PG_DBNAME']
        conn_str = f'postgresql://integration_user:integration_password@localhost:5432/{db_name}'
        with psycopg.connect(conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute('SELECT extname FROM pg_extension WHERE extname = %s', ('pg_cron',))
                if not cur.fetchone():
                    raise Exception('pg_cron extension not found')
                cur.execute('SELECT extname FROM pg_extension WHERE extname = %s', ('roaringbitmap',))
                if not cur.fetchone():
                    print('roaringbitmap extension not found (optional)')
        "

    - name: Run tests
      shell: micromamba-shell {0}
      run: |
        PYTEST_FLAGS="--ci --pattern ${{ matrix.test-pattern.pattern }} --verbose"
        
        if [[ "${{ matrix.test-pattern.parallel }}" == "true" ]]; then
          PYTEST_FLAGS="$PYTEST_FLAGS --parallel"
        fi
        
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
          PYTEST_FLAGS="$PYTEST_FLAGS --coverage"
        fi
        
        ./scripts/run_integration_tests.sh $PYTEST_FLAGS --no-setup

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.test-pattern.name }}
        path: |
          htmlcov/
          .coverage
          pytest-results.xml
          /tmp/ci_rocksdb*/
          /tmp/ci_rocksdict*/
        retention-days: 7

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        file: ./coverage.xml
        flags: integration-${{ matrix.test-pattern.name }}

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [build-postgres-image, integration-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    services:
      postgres:
        image: ghcr.io/mpoppinga/postgres-test-extensions:${{ needs.build-postgres-image.outputs.image-tag }}
        env:
          POSTGRES_DB: partitioncache_integration
          POSTGRES_USER: integration_user
          POSTGRES_PASSWORD: integration_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U integration_user -d partitioncache_integration"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      UNIQUE_DB_NAME: partitioncache_e2e_${{ github.run_id }}
      TEMPLATE_DB_NAME: partitioncache_integration
      CACHE_BACKEND: postgresql_array
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: integration_user
      PG_PASSWORD: integration_password
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: integration_user
      DB_PASSWORD: integration_password
      PG_QUEUE_HOST: localhost
      PG_QUEUE_PORT: 5432
      PG_QUEUE_USER: integration_user
      PG_QUEUE_PASSWORD: integration_password
      QUERY_QUEUE_PROVIDER: postgresql

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: .github/micromamba-env.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install PartitionCache
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[testing,db]"
        pip install pytest-xdist  # Additional for parallel execution

    - name: Create and configure test database
      shell: micromamba-shell {0}
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..30}; do
          if python -c "import psycopg; psycopg.connect('postgresql://integration_user:integration_password@localhost:5432/$TEMPLATE_DB_NAME')" 2>/dev/null; then
            echo "PostgreSQL ready"
            break
          fi
          sleep 2
        done

        echo "Creating test database: $UNIQUE_DB_NAME from template $TEMPLATE_DB_NAME"
        python -c "
        import os
        import psycopg
        from psycopg import sql
        db_name = os.environ['UNIQUE_DB_NAME']
        template_db = os.environ['TEMPLATE_DB_NAME']
        conn_str = f'postgresql://integration_user:integration_password@localhost:5432/{template_db}'
        with psycopg.connect(conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(sql.SQL('CREATE DATABASE {} TEMPLATE {}').format(
                    sql.Identifier(db_name),
                    sql.Identifier(template_db)
                ))
        "

        # Set the database name for subsequent steps
        echo "PG_DBNAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV
        echo "DB_NAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV
        echo "PG_QUEUE_DB=$UNIQUE_DB_NAME" >> $GITHUB_ENV

    - name: Run E2E tests
      shell: micromamba-shell {0}
      run: |
        ./scripts/run_integration_tests.sh \
          --ci \
          --no-setup \
          --pattern test_end_to_end_workflows \
          --verbose \
          --coverage

    - name: Upload E2E artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          htmlcov/
          .coverage
          pytest-results.xml
        retention-days: 7

  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [build-postgres-image, integration-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    services:
      postgres:
        image: ghcr.io/mpoppinga/postgres-test-extensions:${{ needs.build-postgres-image.outputs.image-tag }}
        env:
          POSTGRES_DB: partitioncache_integration
          POSTGRES_USER: integration_user
          POSTGRES_PASSWORD: integration_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U integration_user -d partitioncache_integration"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      UNIQUE_DB_NAME: partitioncache_perf_${{ github.run_id }}
      TEMPLATE_DB_NAME: partitioncache_integration
      CACHE_BACKEND: postgresql_array
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: integration_user
      PG_PASSWORD: integration_password
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: integration_user
      DB_PASSWORD: integration_password

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: .github/micromamba-env.yml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install PartitionCache
      shell: micromamba-shell {0}
      run: |
        pip install -e ".[testing,db]"
        pip install pytest-xdist  # Additional for parallel execution

    - name: Create and configure test database
      shell: micromamba-shell {0}
      run: |
        echo "Waiting for PostgreSQL..."
        for i in {1..30}; do
          if python -c "import psycopg; psycopg.connect('postgresql://integration_user:integration_password@localhost:5432/$TEMPLATE_DB_NAME')" 2>/dev/null; then
            echo "PostgreSQL ready"
            break
          fi
          sleep 2
        done

        echo "Creating test database: $UNIQUE_DB_NAME from template $TEMPLATE_DB_NAME"
        python -c "
        import os
        import psycopg
        from psycopg import sql
        db_name = os.environ['UNIQUE_DB_NAME']
        template_db = os.environ['TEMPLATE_DB_NAME']
        conn_str = f'postgresql://integration_user:integration_password@localhost:5432/{template_db}'
        with psycopg.connect(conn_str, autocommit=True) as conn:
            with conn.cursor() as cur:
                cur.execute(sql.SQL('CREATE DATABASE {} TEMPLATE {}').format(
                    sql.Identifier(db_name),
                    sql.Identifier(template_db)
                ))
        "

        # Set the database name for subsequent steps
        echo "PG_DBNAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV
        echo "DB_NAME=$UNIQUE_DB_NAME" >> $GITHUB_ENV

    - name: Run performance tests
      shell: micromamba-shell {0}
      run: |
        ./scripts/run_integration_tests.sh \
          --ci \
          --no-setup \
          --pattern performance \
          --verbose

    - name: Upload performance artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-test-results
        path: |
          pytest-results.xml
          performance-results/
        retention-days: 30

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [integration-tests, e2e-tests, performance-tests]
    if: always()
    
    steps:
    - name: Check results
      run: |
        echo "Integration Test Summary"
        echo "======================="
        
        if [[ "${{ needs.integration-tests.result }}" == "success" ]]; then
          echo "Integration tests: PASSED"
        else
          echo "Integration tests: FAILED"
          exit 1
        fi
        
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          if [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "E2E tests: PASSED"
          else
            echo "E2E tests: FAILED"
            exit 1
          fi
          
          if [[ "${{ needs.performance-tests.result }}" == "success" ]]; then
            echo "Performance tests: PASSED"
          else
            echo "Performance tests: FAILED"
            exit 1
          fi
        fi
        
        echo "All tests completed successfully"
